CREATE TABLE core.app_users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar UNIQUE,
  nombre varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.dim_variedades (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id int,
  variedad varchar,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_categorias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id int,
  categoria varchar,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_calibres (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id int,
  calibre varchar,
  convencion_id int,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_convenciones (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  convencion varchar,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_medios_pago (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_grupos_egresos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar UNIQUE,
  descripcion text,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_tipos_egreso (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  grupo_id int,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_modelos_comerciales (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_tipos_economicos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_estados_despacho (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_estados_venta (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_estados_venta_facturacion (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_estados_venta_pago (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_estados_compra (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_tipos_clientes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_estados_pedido (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_tipos_venta (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_entity_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar UNIQUE,
  descripcion text,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_event_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar UNIQUE,
  descripcion text,
  is_active boolean DEFAULT true
);

CREATE TABLE core.terceros (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut varchar UNIQUE,
  nombre varchar,
  alias varchar,
  telefono varchar,
  direccion varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.terceros_cliente (
  tercero_id int PRIMARY KEY,
  tipo_id int,
  vendedor_id int,
  factura boolean DEFAULT false,
  factura_despacho boolean DEFAULT false,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.terceros_proveedor (
  tercero_id int PRIMARY KEY,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.terceros_vendedor (
  tercero_id int PRIMARY KEY,
  modelo_comercial_id int,
  comision numeric(6,4),
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.destinatarios (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id int,
  nombre varchar,
  rut varchar,
  telefono varchar,
  direccion varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.trabajadores (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar,
  apellido varchar,
  cargo varchar,
  rut varchar UNIQUE,
  telefono varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.vehiculos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alias varchar UNIQUE,
  patente varchar,
  tipo_vehiculo varchar,
  marca varchar,
  modelo varchar,
  anio int,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.productos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar,
  unidad varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.codigos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.pedidos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  cliente_id int,
  destinatario_id int,
  estado_id int,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.pedidos_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  codigo_id int,
  kg numeric(12,3),
  precio_unit numeric(14,2),
  precio_total numeric(14,2),
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.entregas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id int UNIQUE,
  fecha date,
  receptor varchar,
  foto_url text,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.ventas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  pedido_id int UNIQUE,
  cliente_id int,
  destinatario_id int,
  tipo_id int,
  estado_venta_id int,
  estado_despacho_id int,
  estado_facturacion_id int,
  estado_pago_id int,
  factura varchar,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.ventas_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  codigo_id int,
  kg numeric(12,3),
  precio_unit numeric(14,2),
  precio_total numeric(14,2),
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.pagos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  cliente_id int,
  monto numeric(14,2),
  medio_pago_id int,
  referencia varchar,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.aplicaciones_pago (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pago_id int,
  venta_id int,
  monto_aplicado numeric(14,2),
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.compras_producto (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  codigo_id int,
  proveedor_id int,
  estado_compra_id int,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.compras_producto_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  kg numeric(12,3),
  costo_unit numeric(14,2),
  costo_unit_con_iva numeric(14,2),
  costo_total numeric(14,2),
  costo_total_con_iva numeric(14,2),
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.ingresos_producto (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  nombre_chofer varchar,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.ingresos_producto_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingreso_id int,
  codigo_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  kg numeric(12,3),
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.mermas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  codigo_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  kg numeric(12,3),
  kg_ajustado numeric(12,3),
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.egresos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  tipo_egreso_id int,
  tipo_economico_id int,
  monto numeric(14,2),
  medio_pago_id int,
  vehiculo_id int,
  trabajador_id int,
  vendedor_id int,
  cliente_id int,
  proveedor_id int,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.pagos_compra (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id int,
  egreso_id int,
  monto_aplicado numeric(14,2),
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE ingest.ingest_events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  received_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  event_at timestamptz,
  source_system varchar,
  source_entity varchar,
  external_id varchar,
  idempotency_key varchar,
  respondent_email varchar,
  raw_payload jsonb,
  checksum varchar,
  status varchar,
  error_message text
);

CREATE TABLE ingest.entity_events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingest_event_id int,
  event_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  entity_type_id int,
  entity_id int,
  event_type_id int,
  actor_user_id int,
  actor varchar,
  respondent_email varchar,
  form_timestamp timestamptz,
  external_id varchar,
  status varchar,
  message text,
  payload jsonb
);

CREATE TABLE audit.audit_log (
  id bigserial PRIMARY KEY,
  occurred_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  schema_name varchar,
  table_name varchar,
  action varchar,
  pk jsonb,
  row_before jsonb,
  row_after jsonb,
  changed_fields jsonb,
  actor_user_id int,
  actor varchar,
  ingest_event_id int,
  request_id varchar,
  txid bigint,
  application_name varchar,
  client_addr varchar
);
