CREATE TABLE core.app_users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar UNIQUE,
  nombre varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.dim_varieties (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id int,
  variedad varchar,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id int,
  categoria varchar,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_calibers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id int,
  calibre varchar,
  convencion_id int,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_conventions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  convencion varchar,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_payment_methods (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_expense_groups (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar UNIQUE,
  descripcion text,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_expense_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  grupo_id int,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_commercial_models (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_salesperson_contract_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_salesperson_commission_bases (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_economic_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_shipping_statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_sales_statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_sales_billing_statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_sales_payment_statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_purchase_statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_customer_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_order_statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_sale_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar UNIQUE,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_entity_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar UNIQUE,
  descripcion text,
  is_active boolean DEFAULT true
);

CREATE TABLE core.dim_event_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar UNIQUE,
  descripcion text,
  is_active boolean DEFAULT true
);

CREATE TABLE core.parties (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut varchar UNIQUE,
  nombre varchar,
  alias varchar,
  telefono varchar,
  direccion varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.parties_customer (
  tercero_id int PRIMARY KEY,
  tipo_id int,
  vendedor_id int,
  factura boolean DEFAULT false,
  factura_despacho boolean DEFAULT false,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.parties_supplier (
  tercero_id int PRIMARY KEY,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.parties_salesperson (
  tercero_id int PRIMARY KEY,
  modelo_comercial_id int,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.salesperson_contracts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendedor_id int,
  tipo_id int,
  base_id int,
  tasa_comision numeric(14,6),
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.parties_employee (
  tercero_id int PRIMARY KEY,
  cargo varchar,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.parties_recipient (
  tercero_id int PRIMARY KEY,
  cliente_id int,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.dim_type_assets (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar UNIQUE,
  is_active boolean DEFAULT true
);

INSERT INTO core.dim_type_assets (id, nombre, is_active)
VALUES (1, 'vehiculo', true)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE core.assets (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alias varchar UNIQUE,
  tipo_activo_id int
);

CREATE TABLE core.assets_vehicles (
  activo_id int PRIMARY KEY,
  patente varchar,
  tipo varchar,
  marca varchar,
  modelo varchar,
  anio int,
  is_active boolean DEFAULT true
);

CREATE TABLE core.products (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar,
  unidad varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.codes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz
);

CREATE TABLE core.orders (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  cliente_id int,
  destinatario_id int,
  estado_id int,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.order_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  codigo_id int,
  kg numeric(12,3),
  precio_unit numeric(14,2),
  precio_total numeric(14,2),
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.deliveries (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id int UNIQUE,
  fecha date,
  receptor varchar,
  foto_url text,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.sales (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  pedido_id int UNIQUE,
  cliente_id int,
  destinatario_id int,
  tipo_id int,
  estado_venta_id int,
  estado_despacho_id int,
  estado_facturacion_id int,
  estado_pago_id int,
  factura varchar,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.sale_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  codigo_id int,
  kg numeric(12,3),
  precio_unit numeric(14,2),
  precio_total numeric(14,2),
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.payments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  cliente_id int,
  monto numeric(14,2),
  medio_pago_id int,
  referencia varchar,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.payment_applications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pago_id int,
  venta_id int,
  monto_aplicado numeric(14,2),
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.product_purchases (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  codigo_id int,
  proveedor_id int,
  estado_compra_id int,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.product_purchase_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  kg numeric(12,3),
  costo_unit numeric(14,2),
  costo_unit_con_iva numeric(14,2),
  costo_total numeric(14,2),
  costo_total_con_iva numeric(14,2),
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.product_receipts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  nombre_chofer varchar,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.product_receipt_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingreso_id int,
  codigo_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  kg numeric(12,3),
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.product_losses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  codigo_id int,
  producto_id int,
  variedad_id int,
  categoria_id int,
  calibre_id int,
  kg numeric(12,3),
  kg_ajustado numeric(12,3),
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.expenses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date,
  tipo_egreso_id int,
  tipo_economico_id int,
  monto numeric(14,2),
  medio_pago_id int,
  activo_id int,
  actor_id int,
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE core.purchase_payment_applications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id int,
  egreso_id int,
  monto_aplicado numeric(14,2),
  observaciones text,
  created_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by_user_id int,
  ingest_event_id int
);

CREATE TABLE ingest.ingest_events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  received_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  event_at timestamptz,
  source_system varchar,
  source_entity varchar,
  external_id varchar,
  idempotency_key varchar,
  respondent_email varchar,
  raw_payload jsonb,
  checksum varchar,
  status varchar,
  error_message text
);

CREATE TABLE ingest.entity_events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingest_event_id int,
  event_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  entity_type_id int,
  entity_id int,
  event_type_id int,
  actor_user_id int,
  actor varchar,
  respondent_email varchar,
  form_timestamp timestamptz,
  external_id varchar,
  status varchar,
  message text,
  payload jsonb
);

CREATE TABLE audit.audit_log (
  id bigserial PRIMARY KEY,
  occurred_at timestamptz DEFAULT (CURRENT_TIMESTAMP),
  schema_name varchar,
  table_name varchar,
  action varchar,
  pk jsonb,
  row_before jsonb,
  row_after jsonb,
  changed_fields jsonb,
  actor_user_id int,
  actor varchar,
  ingest_event_id int,
  request_id varchar,
  txid bigint,
  application_name varchar,
  client_addr varchar
);
