CREATE TABLE "APP_USERS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "nombre" varchar,
  "is_active" boolean DEFAULT true,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz
);

CREATE TABLE "PRODUCTOS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "unidad" varchar,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_VARIEDAD" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" int,
  "variedad" varchar,
  "is_active" boolean DEFAULT true,
  "observaciones" text
);

CREATE TABLE "DIM_CATEGORIA" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" int,
  "categoria" varchar,
  "is_active" boolean DEFAULT true,
  "observaciones" text
);

CREATE TABLE "DIM_CALIBRES" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto_id" int,
  "calibre" varchar,
  "convencion" varchar,
  "is_active" boolean DEFAULT true,
  "observaciones" text
);

CREATE TABLE "DIM_MEDIO_PAGO" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_GRUPOS_EGRESOS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE,
  "descripcion" text
);

CREATE TABLE "DIM_TIPO_EGRESOS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar,
  "grupo_id" int,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_TIPO_ECONOMICO" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_TIPO_MOV" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar,
  "operacion" varchar,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_ESTADO_DESPACHO" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_ESTADO_VENTA" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_ESTADO_VENTA_FACTURACION" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_ESTADO_VENTA_PAGO" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_ESTADO_COMPRA" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_TIPO_CLIENTE" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_ESTADO_PEDIDO" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_TIPO_VENTA" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar UNIQUE,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_VEHICULOS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "alias" varchar,
  "patente" varchar,
  "tipo_vehiculo" varchar,
  "marca" varchar,
  "modelo" varchar,
  "anio" int,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "TRABAJADORES" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "apellido" varchar,
  "cargo" varchar,
  "rut" varchar UNIQUE,
  "telefono" varchar,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "CUENTAS_BANCARIAS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titular" varchar,
  "rut" varchar,
  "banco" varchar,
  "tipo_cuenta" varchar,
  "numero_cuenta" varchar,
  "factura" boolean DEFAULT false
);

CREATE TABLE "VENDEDORES" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "modelo_comercial" varchar,
  "cliente_id" int,
  "telefono" varchar,
  "comision" numeric(6,4),
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_ENTITY_TYPE" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "descripcion" text,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "DIM_EVENT_TYPE" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "descripcion" text,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "TERCEROS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rut" varchar UNIQUE,
  "nombre" varchar,
  "alias" varchar,
  "telefono" varchar,
  "direccion" varchar,
  "is_active" boolean DEFAULT true,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "TERCEROS_CLIENTE" (
  "tercero_id" int PRIMARY KEY,
  "tipo_id" int,
  "vendedor_id" int,
  "factura" boolean DEFAULT false,
  "factura_despacho" boolean DEFAULT false,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "TERCEROS_PROVEEDOR" (
  "tercero_id" int PRIMARY KEY,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "DESTINATARIOS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int,
  "nombre" varchar,
  "rut" varchar,
  "telefono" varchar,
  "direccion" varchar,
  "is_active" boolean DEFAULT true,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "PEDIDOS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "cliente_id" int,
  "destinatario_id" int,
  "estado_id" int,
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "PEDIDOS_ITEMS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" int,
  "producto_id" int,
  "variedad_id" int,
  "categoria_id" int,
  "calibre_id" int,
  "codigo" varchar,
  "kg" numeric(12,3),
  "precio_unit" numeric(14,2),
  "precio_total" numeric(14,2),
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "ENTREGAS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_id" int UNIQUE,
  "fecha" date,
  "receptor" varchar,
  "foto_url" text,
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "VENTAS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "pedido_id" int UNIQUE,
  "cliente_id" int,
  "destinatario_id" int,
  "tipo_id" int,
  "estado_venta_id" int,
  "estado_despacho_id" int,
  "estado_facturacion_id" int,
  "estado_pago_id" int,
  "num_guia" varchar,
  "factura" varchar,
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "VENTAS_ITEMS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venta_id" int,
  "producto_id" int,
  "variedad_id" int,
  "categoria_id" int,
  "calibre_id" int,
  "codigo" varchar,
  "kg" numeric(12,3),
  "precio_unit" numeric(14,2),
  "precio_total" numeric(14,2),
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "PAGOS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "cliente_id" int,
  "monto" numeric(14,2),
  "medio_pago_id" int,
  "referencia" varchar,
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "APLICACIONES_PAGO" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pago_id" int,
  "venta_id" int,
  "monto_aplicado" numeric(14,2),
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "COMPRAS_PRODUCTO" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "codigo" varchar,
  "proveedor_id" int,
  "estado_compra_id" int,
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "COMPRAS_PRODUCTO_ITEMS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compra_id" int,
  "producto_id" int,
  "variedad_id" int,
  "categoria_id" int,
  "calibre_id" int,
  "kg" numeric(12,3),
  "costo_unit" numeric(14,2),
  "costo_unit_con_iva" numeric(14,2),
  "costo_total" numeric(14,2),
  "costo_total_con_iva" numeric(14,2),
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "INGRESOS_PRODUCTO" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "nombre_chofer" varchar,
  "numero_guia" varchar,
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "INGRESOS_PRODUCTO_ITEMS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ingreso_id" int,
  "codigo" varchar,
  "producto_id" int,
  "variedad_id" int,
  "categoria_id" int,
  "calibre_id" int,
  "kg" numeric(12,3),
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "MERMAS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "codigo" varchar,
  "producto_id" int,
  "variedad_id" int,
  "categoria_id" int,
  "calibre_id" int,
  "kg" numeric(12,3),
  "kg_ajustado" numeric(12,3),
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "EGRESOS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "tipo_egreso_id" int,
  "tipo_economico_id" int,
  "monto" numeric(14,2),
  "medio_pago_id" int,
  "vehiculo_id" int,
  "trabajador_id" int,
  "vendedor_id" int,
  "cliente_id" int,
  "proveedor_id" int,
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "PAGOS_COMPRA" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compra_id" int,
  "egreso_id" int,
  "monto_aplicado" numeric(14,2),
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "MOV_STOCK" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "tipo_mov_id" int,
  "producto_id" int,
  "variedad_id" int,
  "categoria_id" int,
  "calibre_id" int,
  "codigo" varchar,
  "kg" numeric(12,3),
  "compra_id" int,
  "venta_id" int,
  "ingreso_id" int,
  "merma_id" int,
  "observaciones" text,
  "created_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamptz,
  "deleted_at" timestamptz,
  "deleted_by_user_id" int,
  "ingest_event_id" int
);

CREATE TABLE "INGEST_EVENTS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "received_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "event_at" timestamptz,
  "source_system" varchar,
  "source_entity" varchar,
  "external_id" varchar,
  "idempotency_key" varchar,
  "respondent_email" varchar,
  "raw_payload" jsonb,
  "checksum" varchar,
  "status" varchar,
  "error_message" text
);

CREATE TABLE "ENTITY_EVENTS" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ingest_event_id" int,
  "event_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "entity_type_id" int,
  "entity_id" int,
  "event_type_id" int,
  "actor_user_id" int,
  "actor" varchar,
  "respondent_email" varchar,
  "form_timestamp" timestamptz,
  "external_id" varchar,
  "status" varchar,
  "message" text,
  "payload" jsonb
);

CREATE TABLE "AUDIT_LOG" (
  "id" bigserial PRIMARY KEY,
  "occurred_at" timestamptz DEFAULT (CURRENT_TIMESTAMP),
  "schema_name" varchar,
  "table_name" varchar,
  "action" varchar,
  "pk" jsonb,
  "row_before" jsonb,
  "row_after" jsonb,
  "changed_fields" jsonb,
  "actor_user_id" int,
  "actor" varchar,
  "ingest_event_id" int,
  "request_id" varchar,
  "txid" bigint,
  "application_name" varchar,
  "client_addr" varchar
);

CREATE UNIQUE INDEX ON "DIM_VARIEDAD" ("producto_id", "variedad");

CREATE UNIQUE INDEX ON "DIM_CATEGORIA" ("producto_id", "categoria");

CREATE UNIQUE INDEX ON "DIM_CALIBRES" ("producto_id", "calibre", "convencion");

CREATE UNIQUE INDEX ON "DIM_TIPO_EGRESOS" ("tipo", "grupo_id");

CREATE UNIQUE INDEX ON "DIM_TIPO_MOV" ("tipo");

CREATE UNIQUE INDEX ON "DIM_VEHICULOS" ("alias");

CREATE UNIQUE INDEX ON "VENDEDORES" ("nombre");

CREATE UNIQUE INDEX ON "DESTINATARIOS" ("cliente_id", "nombre");

CREATE UNIQUE INDEX ON "APLICACIONES_PAGO" ("pago_id", "venta_id");

CREATE UNIQUE INDEX ON "PAGOS_COMPRA" ("compra_id", "egreso_id");

CREATE UNIQUE INDEX ON "INGEST_EVENTS" ("idempotency_key");

CREATE UNIQUE INDEX ON "INGEST_EVENTS" ("source_system", "external_id");

CREATE INDEX ON "ENTITY_EVENTS" ("entity_type_id", "entity_id", "event_at");

COMMENT ON COLUMN "VENDEDORES"."comision" IS 'CHECK (comision >= 0 AND comision <= 1)';

COMMENT ON COLUMN "PEDIDOS_ITEMS"."kg" IS 'CHECK (kg >= 0)';

COMMENT ON COLUMN "PEDIDOS_ITEMS"."precio_unit" IS 'CHECK (precio_unit >= 0)';

COMMENT ON COLUMN "PEDIDOS_ITEMS"."precio_total" IS 'CHECK (precio_total >= 0)';

COMMENT ON COLUMN "VENTAS_ITEMS"."kg" IS 'CHECK (kg >= 0)';

COMMENT ON COLUMN "VENTAS_ITEMS"."precio_unit" IS 'CHECK (precio_unit >= 0)';

COMMENT ON COLUMN "VENTAS_ITEMS"."precio_total" IS 'CHECK (precio_total >= 0)';

COMMENT ON COLUMN "PAGOS"."monto" IS 'CHECK (monto >= 0)';

COMMENT ON COLUMN "APLICACIONES_PAGO"."monto_aplicado" IS 'CHECK (monto_aplicado > 0)';

COMMENT ON COLUMN "COMPRAS_PRODUCTO_ITEMS"."kg" IS 'CHECK (kg >= 0)';

COMMENT ON COLUMN "COMPRAS_PRODUCTO_ITEMS"."costo_unit" IS 'CHECK (costo_unit >= 0)';

COMMENT ON COLUMN "COMPRAS_PRODUCTO_ITEMS"."costo_unit_con_iva" IS 'CHECK (costo_unit_con_iva >= 0)';

COMMENT ON COLUMN "COMPRAS_PRODUCTO_ITEMS"."costo_total" IS 'CHECK (costo_total >= 0)';

COMMENT ON COLUMN "COMPRAS_PRODUCTO_ITEMS"."costo_total_con_iva" IS 'CHECK (costo_total_con_iva >= 0)';

COMMENT ON COLUMN "INGRESOS_PRODUCTO_ITEMS"."kg" IS 'CHECK (kg >= 0)';

COMMENT ON COLUMN "MERMAS"."kg" IS 'CHECK (kg >= 0)';

COMMENT ON COLUMN "MERMAS"."kg_ajustado" IS 'CHECK (kg_ajustado >= 0)';

COMMENT ON COLUMN "EGRESOS"."monto" IS 'CHECK (monto >= 0)';

COMMENT ON COLUMN "PAGOS_COMPRA"."monto_aplicado" IS 'CHECK (monto_aplicado > 0)';

COMMENT ON COLUMN "MOV_STOCK"."kg" IS 'CHECK (kg >= 0)';

ALTER TABLE "TERCEROS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "TERCEROS_CLIENTE" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "TERCEROS_PROVEEDOR" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "DESTINATARIOS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "PEDIDOS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "PEDIDOS_ITEMS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "ENTREGAS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "VENTAS_ITEMS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "PAGOS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "APLICACIONES_PAGO" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "COMPRAS_PRODUCTO" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "COMPRAS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "INGRESOS_PRODUCTO" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "INGRESOS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "MERMAS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "PAGOS_COMPRA" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("deleted_by_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "ENTITY_EVENTS" ADD FOREIGN KEY ("actor_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "AUDIT_LOG" ADD FOREIGN KEY ("actor_user_id") REFERENCES "APP_USERS" ("id") ON DELETE SET NULL;

ALTER TABLE "TERCEROS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "TERCEROS_CLIENTE" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "TERCEROS_PROVEEDOR" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "DESTINATARIOS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "PEDIDOS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "PEDIDOS_ITEMS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "ENTREGAS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "VENTAS_ITEMS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "PAGOS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "APLICACIONES_PAGO" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "COMPRAS_PRODUCTO" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "COMPRAS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "INGRESOS_PRODUCTO" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "INGRESOS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "MERMAS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "PAGOS_COMPRA" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "AUDIT_LOG" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "ENTITY_EVENTS" ADD FOREIGN KEY ("entity_type_id") REFERENCES "DIM_ENTITY_TYPE" ("id") ON DELETE RESTRICT;

ALTER TABLE "ENTITY_EVENTS" ADD FOREIGN KEY ("event_type_id") REFERENCES "DIM_EVENT_TYPE" ("id") ON DELETE RESTRICT;

ALTER TABLE "ENTITY_EVENTS" ADD FOREIGN KEY ("ingest_event_id") REFERENCES "INGEST_EVENTS" ("id") ON DELETE SET NULL;

ALTER TABLE "DIM_VARIEDAD" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "DIM_CATEGORIA" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "DIM_CALIBRES" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "DIM_TIPO_EGRESOS" ADD FOREIGN KEY ("grupo_id") REFERENCES "DIM_GRUPOS_EGRESOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "TERCEROS_CLIENTE" ADD FOREIGN KEY ("tercero_id") REFERENCES "TERCEROS" ("id") ON DELETE CASCADE;

ALTER TABLE "TERCEROS_CLIENTE" ADD FOREIGN KEY ("tipo_id") REFERENCES "DIM_TIPO_CLIENTE" ("id") ON DELETE RESTRICT;

ALTER TABLE "TERCEROS_CLIENTE" ADD FOREIGN KEY ("vendedor_id") REFERENCES "VENDEDORES" ("id") ON DELETE SET NULL;

ALTER TABLE "TERCEROS_PROVEEDOR" ADD FOREIGN KEY ("tercero_id") REFERENCES "TERCEROS" ("id") ON DELETE CASCADE;

ALTER TABLE "DESTINATARIOS" ADD FOREIGN KEY ("cliente_id") REFERENCES "TERCEROS_CLIENTE" ("tercero_id") ON DELETE CASCADE;

ALTER TABLE "VENDEDORES" ADD FOREIGN KEY ("cliente_id") REFERENCES "TERCEROS_CLIENTE" ("tercero_id") ON DELETE SET NULL;

ALTER TABLE "PEDIDOS" ADD FOREIGN KEY ("cliente_id") REFERENCES "TERCEROS_CLIENTE" ("tercero_id") ON DELETE RESTRICT;

ALTER TABLE "PEDIDOS" ADD FOREIGN KEY ("destinatario_id") REFERENCES "DESTINATARIOS" ("id") ON DELETE SET NULL;

ALTER TABLE "PEDIDOS" ADD FOREIGN KEY ("estado_id") REFERENCES "DIM_ESTADO_PEDIDO" ("id") ON DELETE RESTRICT;

ALTER TABLE "PEDIDOS_ITEMS" ADD FOREIGN KEY ("pedido_id") REFERENCES "PEDIDOS" ("id") ON DELETE CASCADE;

ALTER TABLE "PEDIDOS_ITEMS" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "PEDIDOS_ITEMS" ADD FOREIGN KEY ("variedad_id") REFERENCES "DIM_VARIEDAD" ("id") ON DELETE RESTRICT;

ALTER TABLE "PEDIDOS_ITEMS" ADD FOREIGN KEY ("categoria_id") REFERENCES "DIM_CATEGORIA" ("id") ON DELETE RESTRICT;

ALTER TABLE "PEDIDOS_ITEMS" ADD FOREIGN KEY ("calibre_id") REFERENCES "DIM_CALIBRES" ("id") ON DELETE RESTRICT;

ALTER TABLE "ENTREGAS" ADD FOREIGN KEY ("pedido_id") REFERENCES "PEDIDOS" ("id") ON DELETE CASCADE;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("pedido_id") REFERENCES "PEDIDOS" ("id") ON DELETE SET NULL;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("cliente_id") REFERENCES "TERCEROS_CLIENTE" ("tercero_id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("destinatario_id") REFERENCES "DESTINATARIOS" ("id") ON DELETE SET NULL;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("tipo_id") REFERENCES "DIM_TIPO_VENTA" ("id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("estado_venta_id") REFERENCES "DIM_ESTADO_VENTA" ("id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("estado_despacho_id") REFERENCES "DIM_ESTADO_DESPACHO" ("id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("estado_facturacion_id") REFERENCES "DIM_ESTADO_VENTA_FACTURACION" ("id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS" ADD FOREIGN KEY ("estado_pago_id") REFERENCES "DIM_ESTADO_VENTA_PAGO" ("id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS_ITEMS" ADD FOREIGN KEY ("venta_id") REFERENCES "VENTAS" ("id") ON DELETE CASCADE;

ALTER TABLE "VENTAS_ITEMS" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS_ITEMS" ADD FOREIGN KEY ("variedad_id") REFERENCES "DIM_VARIEDAD" ("id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS_ITEMS" ADD FOREIGN KEY ("categoria_id") REFERENCES "DIM_CATEGORIA" ("id") ON DELETE RESTRICT;

ALTER TABLE "VENTAS_ITEMS" ADD FOREIGN KEY ("calibre_id") REFERENCES "DIM_CALIBRES" ("id") ON DELETE RESTRICT;

ALTER TABLE "PAGOS" ADD FOREIGN KEY ("cliente_id") REFERENCES "TERCEROS_CLIENTE" ("tercero_id") ON DELETE RESTRICT;

ALTER TABLE "PAGOS" ADD FOREIGN KEY ("medio_pago_id") REFERENCES "DIM_MEDIO_PAGO" ("id") ON DELETE RESTRICT;

ALTER TABLE "APLICACIONES_PAGO" ADD FOREIGN KEY ("pago_id") REFERENCES "PAGOS" ("id") ON DELETE CASCADE;

ALTER TABLE "APLICACIONES_PAGO" ADD FOREIGN KEY ("venta_id") REFERENCES "VENTAS" ("id") ON DELETE CASCADE;

ALTER TABLE "COMPRAS_PRODUCTO" ADD FOREIGN KEY ("proveedor_id") REFERENCES "TERCEROS_PROVEEDOR" ("tercero_id") ON DELETE SET NULL;

ALTER TABLE "COMPRAS_PRODUCTO" ADD FOREIGN KEY ("estado_compra_id") REFERENCES "DIM_ESTADO_COMPRA" ("id") ON DELETE RESTRICT;

ALTER TABLE "COMPRAS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("compra_id") REFERENCES "COMPRAS_PRODUCTO" ("id") ON DELETE CASCADE;

ALTER TABLE "COMPRAS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "COMPRAS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("variedad_id") REFERENCES "DIM_VARIEDAD" ("id") ON DELETE RESTRICT;

ALTER TABLE "COMPRAS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("categoria_id") REFERENCES "DIM_CATEGORIA" ("id") ON DELETE RESTRICT;

ALTER TABLE "COMPRAS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("calibre_id") REFERENCES "DIM_CALIBRES" ("id") ON DELETE RESTRICT;

ALTER TABLE "INGRESOS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("ingreso_id") REFERENCES "INGRESOS_PRODUCTO" ("id") ON DELETE CASCADE;

ALTER TABLE "INGRESOS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "INGRESOS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("variedad_id") REFERENCES "DIM_VARIEDAD" ("id") ON DELETE RESTRICT;

ALTER TABLE "INGRESOS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("categoria_id") REFERENCES "DIM_CATEGORIA" ("id") ON DELETE RESTRICT;

ALTER TABLE "INGRESOS_PRODUCTO_ITEMS" ADD FOREIGN KEY ("calibre_id") REFERENCES "DIM_CALIBRES" ("id") ON DELETE RESTRICT;

ALTER TABLE "MERMAS" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "MERMAS" ADD FOREIGN KEY ("variedad_id") REFERENCES "DIM_VARIEDAD" ("id") ON DELETE RESTRICT;

ALTER TABLE "MERMAS" ADD FOREIGN KEY ("categoria_id") REFERENCES "DIM_CATEGORIA" ("id") ON DELETE RESTRICT;

ALTER TABLE "MERMAS" ADD FOREIGN KEY ("calibre_id") REFERENCES "DIM_CALIBRES" ("id") ON DELETE RESTRICT;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("tipo_egreso_id") REFERENCES "DIM_TIPO_EGRESOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("tipo_economico_id") REFERENCES "DIM_TIPO_ECONOMICO" ("id") ON DELETE RESTRICT;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("medio_pago_id") REFERENCES "DIM_MEDIO_PAGO" ("id") ON DELETE RESTRICT;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("vehiculo_id") REFERENCES "DIM_VEHICULOS" ("id") ON DELETE SET NULL;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("trabajador_id") REFERENCES "TRABAJADORES" ("id") ON DELETE SET NULL;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("vendedor_id") REFERENCES "VENDEDORES" ("id") ON DELETE SET NULL;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("cliente_id") REFERENCES "TERCEROS_CLIENTE" ("tercero_id") ON DELETE SET NULL;

ALTER TABLE "EGRESOS" ADD FOREIGN KEY ("proveedor_id") REFERENCES "TERCEROS_PROVEEDOR" ("tercero_id") ON DELETE SET NULL;

ALTER TABLE "PAGOS_COMPRA" ADD FOREIGN KEY ("compra_id") REFERENCES "COMPRAS_PRODUCTO" ("id") ON DELETE CASCADE;

ALTER TABLE "PAGOS_COMPRA" ADD FOREIGN KEY ("egreso_id") REFERENCES "EGRESOS" ("id") ON DELETE CASCADE;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("tipo_mov_id") REFERENCES "DIM_TIPO_MOV" ("id") ON DELETE RESTRICT;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("producto_id") REFERENCES "PRODUCTOS" ("id") ON DELETE RESTRICT;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("variedad_id") REFERENCES "DIM_VARIEDAD" ("id") ON DELETE RESTRICT;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("categoria_id") REFERENCES "DIM_CATEGORIA" ("id") ON DELETE RESTRICT;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("calibre_id") REFERENCES "DIM_CALIBRES" ("id") ON DELETE RESTRICT;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("compra_id") REFERENCES "COMPRAS_PRODUCTO" ("id") ON DELETE SET NULL;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("venta_id") REFERENCES "VENTAS" ("id") ON DELETE SET NULL;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("ingreso_id") REFERENCES "INGRESOS_PRODUCTO" ("id") ON DELETE SET NULL;

ALTER TABLE "MOV_STOCK" ADD FOREIGN KEY ("merma_id") REFERENCES "MERMAS" ("id") ON DELETE SET NULL;

ALTER TABLE "PAGOS_COMPRA" ADD FOREIGN KEY ("monto_aplicado") REFERENCES "INGEST_EVENTS" ("received_at");
